# Generated by Django 4.2.1 on 2023-06-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id_artist', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id_song', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('beat', models.BooleanField()),
                ('mix', models.BooleanField()),
                ('master', models.BooleanField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[(0, 'Trap'), (1, 'R&B'), (2, 'Cyber'), (3, 'Reggaeton'), (4, 'Drill'), (5, 'Plugg'), (6, 'Pluggnb')], max_length=1)),
                ('cover_art', models.ImageField(null=True, upload_to='coverart')),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.artist')),
            ],
        ),
    ]
