# Generated by Django 4.2.1 on 2023-06-13 07:22

import django.core.validators
from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), gallery.models.max_value_current_year], verbose_name='year'),
        ),
    ]
