# Generated by Django 4.2.1 on 2023-06-13 07:24

import django.core.validators
from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], validators=[django.core.validators.MinValueValidator(2018), gallery.models.max_value_current_year], verbose_name='year'),
        ),
    ]
