# Generated by Django 4.2.1 on 2023-06-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Trap'), (1, 'R&B'), (2, 'Cyber'), (3, 'Reggaeton'), (4, 'Drill'), (5, 'Plugg'), (6, 'Pluggnb')], max_length=1),
        ),
    ]
